import { ToolLandingLayout } from '@/components/tool-landing-layout';
export const metadata = { title: 'QR Code Generator | PDFilio', description: 'Generate QR codes from PDFs instantly. Create scannable codes for documents and links.' };
export default function Page() {
  const schema = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'QR Code Generator', description: 'Professional QR code generation tool', applicationCategory: 'Utility', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, aggregateRating: { '@type': 'AggregateRating', ratingValue: '4.7', ratingCount: '1800' } };
  return (<ToolLandingLayout toolName="QR Code Generator" toolSlug="qr-code-generator" description="Generate QR codes from PDFs, links, and text. Create scannable codes for instant document sharing." heroImage="/tool-images/qr-code-generator-hero.png" mainContent={`QR Code Generator creates professional QR codes that link directly to your PDFs or any URL. Perfect for document sharing, marketing, and accessibility. Scanners can access content instantly.

Generate high-quality QR codes with custom colors and sizing. Add logos and branding. Create codes for PDFs, links, contact info, WiFi, and more.

Upload PDF or enter URL and generate instant QR code. Customize appearance. Download as PNG, SVG, or PDF.`} useCase={`Document sharing links\nMarketing campaigns\nDigital menus\nBusiness cards\nEvent promotion\nContact information\nWiFi sharing\nProduct information`} testimonials={[{name: 'Ashley Brooks', role: 'Marketing Manager', text: 'QR Code Generator perfect for marketing campaigns. Professional codes instantly!"},{name: 'Daniel Foster', role: 'Business Owner', text: 'Great for sharing PDF catalogs and documents digitally.'},{name: 'Linda Garcia', role: 'Event Organizer', text: 'Use QR codes for event documents and promotions. Works perfectly.'}]} features={['Custom colors','Logo placement','Size options','Format options','Multiple types','High quality','Customizable','Batch generation']} benefits={['Easy sharing','Professional look','Digital access','Marketing boost','Instant scanning','No software needed','Quick setup','Engagement boost']} faqs={[{q: 'PDF linking?', a: 'Yes! Generate QR codes that link directly to PDF files."},{q: 'Custom colors?', a: 'Yes! Customize colors to match branding.'},{q: 'Logo?', a: 'Yes! Add logo or image to QR code center.'},{q: 'Code types?', a: 'URLs, text, contact info, WiFi, SMS, email, and more.'},{q: 'Quality?', a: 'High-resolution codes that scan reliably every time.'},{q: 'Download?', a: 'PNG, SVG, PDF, and EPS formats available.'},{q: 'Tracking?', a: 'Generate codes dynamically for analytics tracking.'},{q: 'Mobile?', a: 'Yes! QR codes work with any smartphone.'},{q: 'Is it free?', a: 'Completely free with unlimited QR code generation.'},{q: 'Professional?', a: 'Perfect for business, marketing, and professional use.'}]} relatedTools={[{name: 'Merge PDF', slug: 'merge-pdf'},{name: 'Compress PDF', slug: 'compress-pdf'},{name: 'PDF to Word', slug: 'pdf-to-word'}]} schema={schema} primaryKeyword="QR code generator" secondaryKeywords={['generate QR code', 'QR code maker', 'free QR code']} />);
}
