export interface Guide {
  slug: string; title: string; description: string; content: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced'; readTime: number;
  keywords: string[]; tools: string[]; relatedGuides: string[]; publishedAt: string;
}

export const guides: Guide[] = [
  {
    slug: 'how-to-compress-pdf', title: 'How to Compress PDF Files: Complete Step-by-Step Guide',
    description: 'Learn practical ways to reduce PDF file size for email, uploads, storage, and sharing while checking the resulting quality.',
    difficulty: 'beginner', readTime: 5,
    keywords: ['compress pdf', 'reduce pdf size', 'pdf compression', 'make pdf smaller'], tools: ['compress-pdf'],
    relatedGuides: ['how-to-merge-pdf', 'how-to-optimize-pdf', 'how-to-compress-pdf-under-2mb'], publishedAt: '2024-01-15T00:00:00Z',
    content: `# How to Compress PDF Files\n\n## Why compress a PDF?\nA smaller PDF is easier to email, upload, store, and share. The amount of reduction depends on the document's images, fonts, embedded content, and current compression.\n\n## Method 1: PDFilio\n1. Open PDFilio's Compress PDF tool.\n2. Select or drop your PDF.\n3. Choose the available compression option.\n4. Review the output and download it when ready.\n\n## Method 2: Reduce the source document\nIf you still need a smaller file, reduce oversized images, remove unnecessary pages or embedded material, and export the source again with appropriate image quality.\n\n## Check quality after compression\nOpen the output and verify text readability, images, page order, and any forms or links you need. Keep the original when the document is important.\n\n## Common reasons a PDF stays large\n- High-resolution photographs\n- Scanned pages\n- Embedded fonts\n- Large graphics\n- Unnecessary metadata or embedded objects\n\n## Best practice\nChoose the smallest output that still meets your purpose. A PDF intended for email may need a different quality level from one intended for printing.`
  },
  {
    slug: 'how-to-merge-pdf', title: 'How to Merge PDF Files into One Document', description: 'Combine multiple PDF files into a single document while keeping the desired page order.', difficulty: 'beginner', readTime: 4,
    keywords: ['merge pdf', 'combine pdf', 'join pdf files'], tools: ['merge-pdf'], relatedGuides: ['how-to-compress-pdf', 'how-to-merge-pdf-for-submission'], publishedAt: '2024-01-16T00:00:00Z',
    content: `# How to Merge PDF Files\n\n## When should you merge PDFs?\nMerging is useful when several related files need to be submitted, shared, archived, or reviewed together.\n\n## Using PDFilio\n1. Open the Merge PDF tool.\n2. Upload the PDFs you want to combine.\n3. Arrange the files in the required order.\n4. Start the merge.\n5. Review the combined document before downloading it.\n\n## Before merging\nCheck page orientation, file names, page order, and whether any document contains sensitive information that should not be combined.\n\n## After merging\nOpen the resulting PDF and confirm that every page is present and readable.`
  },
  {
    slug: 'how-to-split-pdf', title: 'How to Split a PDF into Separate Files', description: 'Extract selected pages or divide a large PDF into smaller documents for sharing and organization.', difficulty: 'beginner', readTime: 4,
    keywords: ['split pdf', 'extract pdf pages', 'separate pdf pages'], tools: ['split-pdf'], relatedGuides: ['how-to-compress-pdf', 'how-to-split-pdf-by-page-range', 'how-to-extract-pages-from-pdf'], publishedAt: '2024-01-17T00:00:00Z',
    content: `# How to Split a PDF\n\n## Why split a PDF?\nSplitting can help when only certain pages need to be submitted, shared, or archived.\n\n## Steps\n1. Open PDFilio's Split PDF tool.\n2. Upload the PDF.\n3. Select the page ranges or splitting option available in the tool.\n4. Start processing.\n5. Open the resulting files and verify the pages.\n\n## Tip\nUse page numbers carefully and review the output before sending an important document.`
  },
  {
    slug: 'how-to-convert-pdf-to-word', title: 'How to Convert PDF to Word for Editing', description: 'Turn a supported PDF into an editable Word document and review the formatting after conversion.', difficulty: 'beginner', readTime: 5,
    keywords: ['pdf to word', 'convert pdf to word', 'editable pdf'], tools: ['pdf-to-word'], relatedGuides: ['how-to-compress-pdf', 'how-to-convert-pdf-to-word-without-losing-formatting'], publishedAt: '2024-01-18T00:00:00Z',
    content: `# How to Convert PDF to Word\n\n## When is PDF to Word useful?\nConversion is useful when you need to revise text, reuse content, or continue editing a document in Word.\n\n## Steps\n1. Open PDFilio's PDF to Word tool.\n2. Upload the supported PDF.\n3. Start the conversion.\n4. Download the Word file using the download button when it is ready.\n5. Review headings, tables, spacing, images, and page breaks.\n\n## Why formatting can change\nPDFs store positioned page content, while Word documents use an editable document structure. Complex layouts, columns, tables, scans, and unusual fonts can therefore require manual cleanup.`
  },
  {
    slug: 'how-to-compress-pdf-for-email', title: 'How to Compress a PDF for Email', description: 'Reduce a PDF before emailing it and check the final size and readability.', difficulty: 'beginner', readTime: 4,
    keywords: ['compress pdf for email', 'pdf too large for email', 'email pdf size'], tools: ['compress-pdf'], relatedGuides: ['how-to-compress-pdf', 'how-to-reduce-pdf-size-for-upload'], publishedAt: '2024-01-19T00:00:00Z',
    content: `# How to Compress a PDF for Email\n\nEmail providers can impose attachment-size limits, so reducing a large PDF can make sharing easier.\n\n## Steps\n1. Open the Compress PDF tool.\n2. Upload your PDF.\n3. Select an available compression level appropriate for screen viewing.\n4. Process the file.\n5. Check the resulting file size and open the PDF to verify readability.\n\n## If it is still too large\nConsider splitting the document into relevant sections or removing unnecessary pages and oversized images from the source.\n\n## Important\nAttachment limits vary by email service. Check the recipient's service if a file is still rejected.`
  },
  {
    slug: 'how-to-compress-pdf-on-mobile', title: 'How to Compress a PDF on Mobile', description: 'A practical workflow for reducing PDF size from a phone or tablet browser.', difficulty: 'beginner', readTime: 4,
    keywords: ['compress pdf on mobile', 'compress pdf android', 'compress pdf iphone'], tools: ['compress-pdf'], relatedGuides: ['how-to-compress-pdf-for-email', 'how-to-reduce-pdf-size-for-upload'], publishedAt: '2024-01-20T00:00:00Z',
    content: `# How to Compress a PDF on Mobile\n\n## Mobile workflow\n1. Open PDFilio in your mobile browser.\n2. Open the Compress PDF tool.\n3. Select the PDF from your device.\n4. Choose the available compression setting.\n5. Wait for processing to finish.\n6. Use the download button to save the resulting file.\n\n## Mobile tips\nUse a stable connection for larger files, make sure your device has enough storage for the output, and review the compressed PDF before sharing it.\n\n## If the PDF is still large\nTry a stronger available compression setting or split the document when only part of it needs to be sent.`
  },
  {
    slug: 'how-to-compress-pdf-under-2mb', title: 'How to Compress a PDF Under 2MB', description: 'Practical steps for reducing a PDF toward a 2MB upload target while checking readability and document quality.', difficulty: 'beginner', readTime: 5,
    keywords: ['compress pdf under 2mb', 'reduce pdf to 2mb', 'pdf under 2mb'], tools: ['compress-pdf'], relatedGuides: ['how-to-compress-pdf', 'how-to-compress-pdf-for-email'], publishedAt: '2026-08-18T00:00:00Z',
    content: `# How to Compress a PDF Under 2MB\n\nA 2MB target is common for online forms and portals, but the achievable size depends on the source PDF.\n\n## Steps\n1. Open PDFilio's Compress PDF tool.\n2. Upload the PDF.\n3. Choose the strongest available compression that still preserves the quality you need.\n4. Process the file and check the resulting size.\n5. Open the PDF and verify text, images, page order, and forms.\n\n## If the file is still above 2MB\nRemove unnecessary pages, reduce oversized source images, or split the document when the destination accepts multiple files. Re-exporting a source document can also help when it contains unusually large images or embedded objects.\n\n## Important\nThere is no universal compression ratio. A photo-heavy or scanned PDF may remain larger than a text-heavy PDF after the same compression setting.`
  },
  {
    slug: 'how-to-reduce-pdf-size-for-upload', title: 'How to Reduce PDF Size for Online Uploads', description: 'Reduce a PDF before uploading it to a form, portal, application, or website and verify the final file.', difficulty: 'beginner', readTime: 5,
    keywords: ['reduce pdf size for upload', 'compress pdf for upload', 'pdf upload size'], tools: ['compress-pdf'], relatedGuides: ['how-to-compress-pdf-under-2mb', 'how-to-compress-pdf-on-mobile'], publishedAt: '2026-08-18T00:00:00Z',
    content: `# How to Reduce PDF Size for Online Uploads\n\nOnline portals often set file-size limits. The first step is to identify the portal's limit, then reduce the PDF while keeping the information readable.\n\n## Recommended workflow\n1. Check the portal's maximum file size.\n2. Upload your PDF to PDFilio's Compress PDF tool.\n3. Select an appropriate compression setting.\n4. Process the file.\n5. Compare the resulting size with the portal limit.\n6. Open the output before uploading it.\n\n## When compression is not enough\nRemove pages that are not required, reduce oversized images in the source, or split the PDF if the submission system permits multiple files.\n\n## Final check\nMake sure signatures, tables, images, page order, and readable text are still present before submitting an important document.`
  },
  {
    slug: 'how-to-compress-pdf-for-job-application', title: 'How to Compress a PDF for a Job Application', description: 'Prepare a smaller resume, cover letter, or supporting PDF for an online job application without skipping a quality check.', difficulty: 'beginner', readTime: 4,
    keywords: ['compress pdf for job application', 'resume pdf too large', 'job application pdf size'], tools: ['compress-pdf'], relatedGuides: ['how-to-compress-pdf', 'how-to-reduce-pdf-size-for-upload'], publishedAt: '2026-08-18T00:00:00Z',
    content: `# How to Compress a PDF for a Job Application\n\nA job portal may limit the size of a resume or supporting document. Compression can reduce the file size before upload.\n\n## Steps\n1. Keep the original resume or document as a backup.\n2. Open PDFilio's Compress PDF tool.\n3. Upload the application PDF.\n4. Choose an available compression option.\n5. Process the document.\n6. Open the output and check that your name, contact details, text, images, and page layout remain readable.\n\n## Keep the resume professional\nAvoid compressing so aggressively that text becomes difficult to read or portfolio images become unnecessarily blurry. If a portal has a specific file-size limit, use that limit as the target.`
  },
  {
    slug: 'how-to-merge-pdf-for-submission', title: 'How to Merge PDFs for an Online Submission', description: 'Combine supporting documents into one PDF while planning the correct order and checking the final file before submission.', difficulty: 'beginner', readTime: 5,
    keywords: ['merge pdf for submission', 'combine pdf for application', 'merge documents into one pdf'], tools: ['merge-pdf'], relatedGuides: ['how-to-merge-pdf', 'how-to-reduce-pdf-size-for-upload'], publishedAt: '2026-08-18T00:00:00Z',
    content: `# How to Merge PDFs for an Online Submission\n\nSome application and submission workflows ask for related documents in one PDF. Merging can make the package easier to review when the submission rules allow it.\n\n## Steps\n1. Confirm which documents the submission requires.\n2. Decide the page order, such as cover page, application, supporting documents, and attachments.\n3. Open PDFilio's Merge PDF tool.\n4. Upload the PDFs and arrange them in the required order.\n5. Start the merge.\n6. Review the combined PDF from beginning to end.\n\n## Before uploading\nCheck that all pages are present, readable, correctly oriented, and in the required order. Also confirm the final file size and file type meet the submission rules.`
  },
  {
    slug: 'how-to-split-pdf-by-page-range', title: 'How to Split a PDF by Page Range', description: 'Extract a specific page range from a PDF when only part of a document needs to be shared or submitted.', difficulty: 'beginner', readTime: 4,
    keywords: ['split pdf by page range', 'extract pdf page range', 'pdf pages to separate file'], tools: ['split-pdf'], relatedGuides: ['how-to-split-pdf', 'how-to-extract-pages-from-pdf'], publishedAt: '2026-08-18T00:00:00Z',
    content: `# How to Split a PDF by Page Range\n\nExtracting a page range is useful when a large document contains a smaller section that needs to be shared or submitted separately.\n\n## Steps\n1. Open PDFilio's Split PDF tool.\n2. Upload the PDF.\n3. Select the page range or splitting option supported by the tool.\n4. Start processing.\n5. Open the resulting PDF and verify the first and last page of the extracted section.\n\n## Avoid page-number mistakes\nPDF viewers can display printed page numbers that differ from the PDF's actual page index. Confirm the page positions before processing an important document.`
  },
  {
    slug: 'how-to-extract-pages-from-pdf', title: 'How to Extract Pages from a PDF', description: 'Create a smaller PDF containing only the pages you need for sharing, review, or submission.', difficulty: 'beginner', readTime: 4,
    keywords: ['extract pages from pdf', 'save selected pdf pages', 'remove pages from pdf'], tools: ['split-pdf'], relatedGuides: ['how-to-split-pdf', 'how-to-split-pdf-by-page-range'], publishedAt: '2026-08-18T00:00:00Z',
    content: `# How to Extract Pages from a PDF\n\nExtracting selected pages can be useful when you only need a section of a report, application, manual, or other document.\n\n## Workflow\n1. Open the Split PDF tool.\n2. Upload the source PDF.\n3. Choose the page range or splitting method available.\n4. Process the file.\n5. Open the extracted PDF and confirm that the intended pages are included.\n\n## Privacy and accuracy\nOnly process documents you are permitted to use. Before sharing the extracted file, check that it does not accidentally contain pages or information that should remain private.`
  },
  {
    slug: 'how-to-convert-pdf-to-word-without-losing-formatting', title: 'How to Convert PDF to Word Without Losing Too Much Formatting', description: 'Improve the chances of a clean PDF-to-Word conversion by preparing the source and checking common layout differences.', difficulty: 'intermediate', readTime: 6,
    keywords: ['convert pdf to word without losing formatting', 'pdf to word formatting', 'pdf word conversion tips'], tools: ['pdf-to-word'], relatedGuides: ['how-to-convert-pdf-to-word'], publishedAt: '2026-08-18T00:00:00Z',
    content: `# How to Convert PDF to Word Without Losing Too Much Formatting\n\nPDF-to-Word conversion cannot guarantee identical layout because PDFs and Word documents represent content differently. You can, however, improve the result by preparing the source and reviewing the output.\n\n## Before conversion\n- Prefer a text-based PDF when possible.\n- Avoid extremely complex multi-column layouts when you control the source.\n- Check whether fonts and images are embedded correctly.\n\n## Convert with PDFilio\n1. Open PDFilio's PDF to Word tool.\n2. Upload the supported PDF.\n3. Start conversion.\n4. Download the Word file when it is ready.\n\n## Review the Word document\nCheck headings, tables, images, page breaks, columns, spacing, lists, and special characters. Scanned PDFs may require OCR or additional editing before the result becomes fully editable.`
  },
  {
    slug: 'how-to-combine-scanned-pdfs', title: 'How to Combine Scanned PDFs into One File', description: 'Combine scanned PDF files into one organized document and verify page order and readability.', difficulty: 'beginner', readTime: 5,
    keywords: ['combine scanned pdfs', 'merge scanned documents', 'merge scanned pdf files'], tools: ['merge-pdf'], relatedGuides: ['how-to-merge-pdf', 'how-to-compress-pdf'], publishedAt: '2026-08-18T00:00:00Z',
    content: `# How to Combine Scanned PDFs into One File\n\nScanned documents are often stored as separate PDF files. Merging them can create one organized file for review, storage, or submission.\n\n## Steps\n1. Check that each scanned PDF is readable and correctly oriented.\n2. Open PDFilio's Merge PDF tool.\n3. Upload the scanned PDFs.\n4. Arrange them in the desired order.\n5. Start the merge.\n6. Review the final PDF page by page.\n\n## If the merged file becomes very large\nScanned pages can contain large images. Compress the resulting PDF if appropriate, then verify that text and images remain readable.`
  },
];

export function getGuideBySlug(slug: string) { return guides.find((guide) => guide.slug === slug); }
