import {PDFArray,PDFDict,PDFHexString,PDFName,PDFNumber,PDFRawStream,PDFString,PDFDocument} from 'pdf-lib';
import {md5,RC4,bytesToHex} from './crypto-minimal';
import {encodePasswordLegacy,PasswordEncodingError} from './password-encoding';

const PAD=new Uint8Array([0x28,0xBF,0x4E,0x5E,0x4E,0x75,0x8A,0x41,0x64,0,0x4E,0x56,0xFF,0xFA,0x01,0x08,0x2E,0x2E,0,0xB6,0xD0,0x68,0x3E,0x80,0x2F,0x0C,0xA9,0xFE,0x64,0x53,0x69,0x7A]);
const FLAGS={print:4,modify:8,copy:16,annotate:32,fill:256,extract:512,assemble:1024,hiPrint:2048};
function perms(o:any){let p=0xFFFFF000|0xC0;if(o.allowPrinting!==false)p|=FLAGS.print;if(o.allowModifying!==false)p|=FLAGS.modify;if(o.allowCopying!==false)p|=FLAGS.copy;if(o.allowAnnotating!==false)p|=FLAGS.annotate;if(o.allowFillingForms!==false)p|=FLAGS.fill;if(o.allowExtraction!==false)p|=FLAGS.extract;if(o.allowAssembly!==false)p|=FLAGS.assemble;if(o.allowHighQualityPrint!==false)p|=FLAGS.hiPrint;return p|0}
function pad(p:string){const b=encodePasswordLegacy(p),out=new Uint8Array(32);if(b.length>=32)out.set(b.slice(0,32));else{out.set(b);out.set(PAD.slice(0,32-b.length),b.length)}return out}
function ownerKey(owner:string|undefined,user:string){let h=md5(pad(owner||user));for(let i=0;i<50;i++)h=md5(h);let r=pad(user);for(let i=0;i<20;i++){const k=new Uint8Array(h.length);for(let j=0;j<h.length;j++)k[j]=h[j]^i;r=new RC4(k.slice(0,16)).process(r)}return r}
function encKey(user:string,o:Uint8Array,p:number,id:Uint8Array){const x=new Uint8Array(32+o.length+4+id.length);let n=0;x.set(pad(user),n);n+=32;x.set(o,n);n+=o.length;x[n++]=p&255;x[n++]=(p>>8)&255;x[n++]=(p>>16)&255;x[n++]=(p>>24)&255;x.set(id,n);let h=md5(x);for(let i=0;i<50;i++)h=md5(h.slice(0,16));return h.slice(0,16)}
function userKey(k:Uint8Array,id:Uint8Array){const h=md5(new Uint8Array([...PAD,...id]));let r=new RC4(k).process(h);for(let i=1;i<=19;i++){const kk=new Uint8Array(k.length);for(let j=0;j<k.length;j++)kk[j]=k[j]^i;r=new RC4(kk).process(r)}const out=new Uint8Array(32);out.set(r);return out}
function objKey(dataKey:Uint8Array,obj:number,gen:number){const x=new Uint8Array(dataKey.length+5);x.set(dataKey);x[dataKey.length]=obj&255;x[dataKey.length+1]=(obj>>8)&255;x[dataKey.length+2]=(obj>>16)&255;x[dataKey.length+3]=gen&255;x[dataKey.length+4]=(gen>>8)&255;const h=md5(x);return h.slice(0,Math.min(dataKey.length+5,16))}
function escapeLiteral(b:Uint8Array){const out:string[]=[];for(const x of b){if(x===92)out.push('\\\\');else if(x===40)out.push('\\(');else if(x===41)out.push('\\)');else if(x===13)out.push('\\r');else if(x===10)out.push('\\n');else out.push(String.fromCharCode(x))}return out.join('')}
function signatureDict(d:PDFDict){const t=d.get(PDFName.of('Type'));const s=t&&typeof (t as any).asString==='function'?(t as any).asString():null;if(s==='/Sig'||s==='/DocTimeStamp')return true;if(s!==null)return false;const br=d.get(PDFName.of('ByteRange'));return br instanceof PDFArray&&br.size()===4&&d.has(PDFName.of('Contents'))}
function skip(k:string,sig:boolean){return k==='/Length'||k==='/Filter'||k==='/DecodeParms'||(sig&&k==='/Contents')}
function encObj(o:any,obj:number,gen:number,key:Uint8Array,seen:WeakSet<object>){if(!o||typeof o!=='object'||seen.has(o))return;if(o instanceof PDFString){seen.add(o);o.value=escapeLiteral(new RC4(objKey(key,obj,gen)).process(o.asBytes()))}else if(o instanceof PDFHexString){seen.add(o);o.value=bytesToHex(new RC4(objKey(key,obj,gen)).process(o.asBytes()))}else if(o instanceof PDFDict){seen.add(o);const sig=signatureDict(o);for(const [k,v] of o.entries())if(!skip(k.asString(),sig))encObj(v,obj,gen,key,seen)}else if(o instanceof PDFArray){seen.add(o);for(const v of o.asArray())encObj(v,obj,gen,key,seen)}}
export async function encryptPDF(pdfBytes:Uint8Array,userPassword:string,options:any={}){if(!userPassword)return Promise.reject(new Error('Password is required'));try{const doc=await PDFDocument.load(pdfBytes,{ignoreEncryption:true,updateMetadata:false});if((doc as any).isEncrypted)throw new Error('This PDF is already password-protected. Remove existing protection first.');const ctx=(doc as any).context,trailer=ctx.trailerInfo;let id:Uint8Array;const ids=trailer.ID;const first=ids instanceof PDFArray?ids.get(0):Array.isArray(ids)?ids[0]:undefined;if(first&&typeof (first as any).asBytes==='function'&&(first as any).asBytes().length){id=(first as any).asBytes()}else{id=new Uint8Array(16);crypto.getRandomValues(id);trailer.ID=[PDFHexString.of(bytesToHex(id)),PDFHexString.of(bytesToHex(id))]}
const p=perms(options),o=ownerKey(options.ownerPassword,userPassword),k=encKey(userPassword,o,p,id),u=userKey(k,id),seen=new WeakSet<object>();
for(const [ref,obj] of ctx.enumerateIndirectObjects()){const num=(ref as any).objectNumber,gen=(ref as any).generationNumber||0;if(obj instanceof PDFDict){const f=obj.get(PDFName.of('Filter'));if(f&&(f as any).asString()==='/Standard')continue}if(obj instanceof PDFRawStream){const type=obj.dict.get(PDFName.of('Type'));if(type&&(['/XRef','/Sig'] as string[]).includes(type.toString()))continue;obj.contents=new RC4(objKey(k,num,gen)).process(obj.contents);encObj(obj.dict,num,gen,k,seen)}else encObj(obj,num,gen,k,seen)}
const ed=ctx.obj({Filter:PDFName.of('Standard'),V:PDFNumber.of(2),R:PDFNumber.of(3),Length:PDFNumber.of(128),P:PDFNumber.of(p),O:PDFHexString.of(bytesToHex(o)),U:PDFHexString.of(bytesToHex(u))});trailer.Encrypt=ctx.register(ed);
return await doc.save({useObjectStreams:false,updateFieldAppearances:false})}catch(e){if(e instanceof PasswordEncodingError)throw e;throw e}}
