'use client'
import {useRef,useState} from 'react'
export default function RedactPdfTool(){
 const input=useRef<HTMLInputElement>(null);const[file,setFile]=useState<File|null>(null);const[x,setX]=useState('0');const[y,setY]=useState('0');const[w,setW]=useState('100');const[h,setH]=useState('40');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[url,setUrl]=useState<string|null>(null)
 const revoke=()=>{if(url)URL.revokeObjectURL(url);setUrl(null)}
 async function process(){if(!file)return;setBusy(true);setError('');revoke();try{const fd=new FormData();fd.append('file',file);fd.append('x',x);fd.append('y',y);fd.append('width',w);fd.append('height',h);const r=await fetch('/api/convert/redact-pdf',{method:'POST',body:fd});if(!r.ok){const d=await r.json().catch(()=>null);throw new Error(d?.error||'Redaction failed.')}setUrl(URL.createObjectURL(await r.blob()))}catch(e){setError(e instanceof Error?e.message:'Redaction failed.')}finally{setBusy(false)}}
 function reset(){revoke();setFile(null);setX('0');setY('0');setW('100');setH('40');setError('');if(input.current)input.current.value=''}
 return <section className="mx-auto w-full max-w-3xl px-4 py-8"><div className="rounded-2xl border bg-background p-5 shadow-sm sm:p-7"><h1 className="text-2xl font-bold sm:text-3xl">Redact PDF</h1><p className="mt-2 text-muted-foreground">Cover the same rectangular area on every page with an opaque black redaction box.</p><input ref={input} type="file" accept=".pdf,application/pdf" onChange={e=>{revoke();setFile(e.target.files?.[0]??null);setError('')}} className="mt-6 block w-full rounded-lg border p-3 text-sm"/>
 <div className="mt-5 grid grid-cols-2 gap-4"><label className="text-sm font-medium">X<input type="number" min="0" value={x} onChange={e=>setX(e.target.value)} disabled={!file||busy} className="mt-2 w-full rounded-lg border px-3 py-3"/></label><label className="text-sm font-medium">Y<input type="number" min="0" value={y} onChange={e=>setY(e.target.value)} disabled={!file||busy} className="mt-2 w-full rounded-lg border px-3 py-3"/></label><label className="text-sm font-medium">Width<input type="number" min="1" value={w} onChange={e=>setW(e.target.value)} disabled={!file||busy} className="mt-2 w-full rounded-lg border px-3 py-3"/></label><label className="text-sm font-medium">Height<input type="number" min="1" value={h} onChange={e=>setH(e.target.value)} disabled={!file||busy} className="mt-2 w-full rounded-lg border px-3 py-3"/></label></div>
 <div className="mt-4 rounded-lg border p-3 text-sm text-amber-700">Important: this workflow draws an opaque rectangle; it does not remove the underlying PDF text/content. Do not use it as secure legal redaction.</div>
 <div className="mt-5 flex gap-3"><button onClick={process} disabled={!file||busy} className="rounded-lg bg-primary px-5 py-3 font-medium text-primary-foreground disabled:opacity-50">{busy?'Processing…':'Apply Redaction Box'}</button>{file&&<button onClick={reset} className="rounded-lg border px-5 py-3 font-medium">Reset</button>}</div>{error&&<p className="mt-4 text-sm text-red-600" role="alert">{error}</p>}{url&&<div className="mt-5 rounded-lg border p-4"><p className="font-medium text-green-700">Processed PDF is ready.</p><a href={url} download={file?.name.replace(/\.pdf$/i,'')+'_redacted.pdf'} className="mt-3 inline-flex rounded-lg border px-5 py-3 font-medium">Download PDF</a></div>}</div></section>
}