'use client'
import {useRef,useState} from 'react'
import {PDFDocument} from 'pdf-lib'
export default function RemovePagesTool(){
 const inputRef=useRef<HTMLInputElement>(null),[file,setFile]=useState<File|null>(null),[count,setCount]=useState<number|null>(null),[pages,setPages]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[url,setUrl]=useState<string|null>(null)
 function clear(){if(url)URL.revokeObjectURL(url);setUrl(null)}
 async function selectFile(f:File|null){clear();setStatus('');setCount(null);setFile(f);setPages('');if(!f)return;if(f.type!=='application/pdf'&&!f.name.toLowerCase().endsWith('.pdf')){setStatus('Please select a PDF file.');setFile(null);return}if(f.size>100*1024*1024){setStatus('PDFs must be 100 MB or smaller.');setFile(null);return}try{setCount((await PDFDocument.load(await f.arrayBuffer())).getPageCount())}catch{setStatus('This PDF could not be read.');setFile(null)}}
 async function submit(){if(!file||!pages.trim())return;setBusy(true);clear();setStatus('Removing selected pages…');try{const fd=new FormData();fd.append('file',file);fd.append('pages',pages);const r=await fetch('/api/convert/remove-pages',{method:'POST',body:fd});if(!r.ok){const d=await r.json().catch(()=>null);throw new Error(d?.error||'Page removal failed.')}setUrl(URL.createObjectURL(await r.blob()));setStatus('Done — your PDF is ready.')}catch(e){setStatus(e instanceof Error?e.message:'Page removal failed.')}finally{setBusy(false)}}
 function reset(){clear();setFile(null);setCount(null);setPages('');setStatus('');if(inputRef.current)inputRef.current.value=''}
 return <section className="mx-auto w-full max-w-3xl px-4 py-8"><div className="rounded-2xl border bg-background p-5 shadow-sm sm:p-7"><h1 className="text-2xl font-bold sm:text-3xl">Remove Pages from PDF</h1><p className="mt-2 text-muted-foreground">Delete unwanted pages and download a new PDF. Your original file stays unchanged.</p><input ref={inputRef} type="file" accept=".pdf,application/pdf" onChange={e=>selectFile(e.target.files?.[0]??null)} className="mt-6 block w-full rounded-lg border p-3 text-sm"/>{file&&<div className="mt-4 rounded-lg border p-4 text-sm"><b>{file.name}</b><div className="mt-1 text-muted-foreground">{count??'…'} pages · {(file.size/1024/1024).toFixed(2)} MB · max 100 MB</div></div>}<label className="mt-5 block text-sm font-medium">Pages to remove<input value={pages} onChange={e=>setPages(e.target.value)} placeholder="Example: 2, 5, 8" disabled={!file||busy} className="mt-2 w-full rounded-lg border px-3 py-3"/></label><p className="mt-2 text-xs text-muted-foreground">Enter original page numbers separated by commas. At least one page must remain.</p><div className="mt-5 flex gap-3"><button type="button" onClick={submit} disabled={!file||!pages.trim()||busy} className="rounded-lg bg-primary px-5 py-3 font-medium text-primary-foreground disabled:opacity-50">{busy?'Removing…':'Remove Pages'}</button>{(file||url)&&<button type="button" onClick={reset} className="rounded-lg border px-5 py-3">Reset</button>}</div>{status&&<p className="mt-4 text-sm" role="status">{status}</p>}{url&&<a href={url} download={file?.name.replace(/\.pdf$/i,'')+'_pages-removed.pdf'} className="mt-4 inline-flex rounded-lg border px-5 py-3 font-medium">Download PDF</a>}</div></section>
}