'use client';
import { useEffect,useState } from 'react';
import { Download, PenLine } from 'lucide-react';
import FileUploader from '@/components/file-uploader';

export default function SignpdfTool(){
 const [file,setFile]=useState<File|null>(null),[signature,setSignature]=useState(''),[page,setPage]=useState('1'),[x,setX]=useState('72'),[y,setY]=useState('72'),[fontSize,setFontSize]=useState('24'),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[url,setUrl]=useState<string|null>(null);
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);
 const sign=async()=>{if(!file)return;setError(null);setBusy(true);try{const f=new FormData();f.append('file',file);f.append('signature',signature);f.append('page',page);f.append('x',x);f.append('y',y);f.append('fontSize',fontSize);const r=await fetch('/api/convert/sign-pdf',{method:'POST',body:f});if(!r.ok){const d=await r.json().catch(()=>null);throw new Error(d?.error||'Unable to sign PDF.')}setUrl(URL.createObjectURL(await r.blob()))}catch(e){setError(e instanceof Error?e.message:'Unable to sign PDF.')}finally{setBusy(false)}};
 const reset=()=>{if(url)URL.revokeObjectURL(url);setUrl(null);setFile(null);setSignature('');setError(null)};
 return <section className="min-h-screen bg-gradient-to-b from-blue-50 to-white py-12 md:py-20"><div className="container mx-auto max-w-2xl px-4"><div className="text-center mb-10"><div className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-blue-100 text-blue-700"><PenLine className="h-7 w-7"/></div><h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-3">Sign PDF Online</h1><p className="text-lg text-gray-600">Add a visible electronic signature mark to a PDF page.</p></div><div className="bg-white rounded-2xl shadow-lg p-6 md:p-8">{!url&&<FileUploader accept=".pdf,application/pdf" onFileSelected={f=>setFile(f[0]||null)} maxSize={100}/>}
 {file&&!url&&<div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 text-sm font-medium text-gray-700">Signature text<input value={signature} onChange={e=>setSignature(e.target.value)} maxLength={200} className="mt-1 w-full rounded-lg border px-3 py-3" placeholder="Type your name or signature"/></label><label className="text-sm font-medium text-gray-700">Page<input type="number" min="1" value={page} onChange={e=>setPage(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-3"/></label><label className="text-sm font-medium text-gray-700">Font size<input type="number" min="8" max="72" value={fontSize} onChange={e=>setFontSize(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-3"/></label><label className="text-sm font-medium text-gray-700">X position (points)<input type="number" min="0" value={x} onChange={e=>setX(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-3"/></label><label className="text-sm font-medium text-gray-700">Y position (points)<input type="number" min="0" value={y} onChange={e=>setY(e.target.value)} className="mt-1 w-full rounded-lg border px-3 py-3"/></label><p className="sm:col-span-2 text-xs text-gray-500">The signature is added as visible italic text. It is not a certificate-based digital signature.</p></div>}
 {error&&<div className="mt-5 rounded-lg border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</div>}
 {!url?<button onClick={sign} disabled={!file||!signature.trim()||busy} className="w-full mt-6 rounded-lg bg-blue-600 px-6 py-3 font-semibold text-white hover:bg-blue-700 disabled:bg-gray-400">{busy?'Signing PDF...':'Sign PDF'}</button>:<div className="text-center mt-4"><p className="text-green-600 font-semibold mb-4">Signature added successfully.</p><a href={url} download={(file?.name.replace(/\.pdf$/i,'')||'document')+'_signed.pdf'} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-8 py-3 font-semibold text-white"><Download className="h-5 w-5"/>Download Signed PDF</a><button onClick={reset} className="ml-3 rounded-lg bg-gray-200 px-6 py-3 font-semibold">Sign Another</button></div>}</div></div></section>
}
