'use client'
import {useRef,useState} from 'react'
export default function WatermarkPdfTool(){
 const input=useRef<HTMLInputElement>(null);const[file,setFile]=useState<File|null>(null);const[text,setText]=useState('CONFIDENTIAL');const[opacity,setOpacity]=useState('0.25');const[fontSize,setFontSize]=useState('36');const[position,setPosition]=useState('center');const[angle,setAngle]=useState('-45');const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[url,setUrl]=useState<string|null>(null)
 const revoke=()=>{if(url)URL.revokeObjectURL(url);setUrl(null)}
 async function process(){if(!file)return;setBusy(true);setError('');revoke();try{const fd=new FormData();fd.append('file',file);fd.append('text',text);fd.append('opacity',opacity);fd.append('fontSize',fontSize);fd.append('position',position);fd.append('angle',angle);const r=await fetch('/api/convert/watermark-pdf',{method:'POST',body:fd});if(!r.ok){const d=await r.json().catch(()=>null);throw new Error(d?.error||'Watermarking failed.')}setUrl(URL.createObjectURL(await r.blob()))}catch(e){setError(e instanceof Error?e.message:'Watermarking failed.')}finally{setBusy(false)}}
 function reset(){revoke();setFile(null);setText('CONFIDENTIAL');setOpacity('0.25');setFontSize('36');setPosition('center');setAngle('-45');setError('');if(input.current)input.current.value=''}
 return <section className="mx-auto w-full max-w-3xl px-4 py-8"><div className="rounded-2xl border bg-background p-5 shadow-sm sm:p-7"><h1 className="text-2xl font-bold sm:text-3xl">Watermark PDF</h1><p className="mt-2 text-muted-foreground">Add a text watermark to every page with controls for opacity, size, angle, and position.</p><input ref={input} type="file" accept=".pdf,application/pdf" onChange={e=>{revoke();setFile(e.target.files?.[0]??null);setError('')}} className="mt-6 block w-full rounded-lg border p-3 text-sm"/>
 <div className="mt-5 grid grid-cols-1 gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Watermark text<input maxLength={120} value={text} onChange={e=>setText(e.target.value)} disabled={!file||busy} className="mt-2 w-full rounded-lg border px-3 py-3"/></label><label className="text-sm font-medium">Position<select value={position} onChange={e=>setPosition(e.target.value)} disabled={!file||busy} className="mt-2 w-full rounded-lg border px-3 py-3"><option value="top-left">Top left</option><option value="top-center">Top center</option><option value="top-right">Top right</option><option value="center">Center</option><option value="bottom-left">Bottom left</option><option value="bottom-center">Bottom center</option><option value="bottom-right">Bottom right</option></select></label><label className="text-sm font-medium">Opacity (0.05–1)<input type="number" min=".05" max="1" step=".05" value={opacity} onChange={e=>setOpacity(e.target.value)} disabled={!file||busy} className="mt-2 w-full rounded-lg border px-3 py-3"/></label><label className="text-sm font-medium">Font size (8–96 pt)<input type="number" min="8" max="96" value={fontSize} onChange={e=>setFontSize(e.target.value)} disabled={!file||busy} className="mt-2 w-full rounded-lg border px-3 py-3"/></label><label className="text-sm font-medium">Angle (-180 to 180°)<input type="number" min="-180" max="180" value={angle} onChange={e=>setAngle(e.target.value)} disabled={!file||busy} className="mt-2 w-full rounded-lg border px-3 py-3"/></label></div>
 <div className="mt-5 flex gap-3"><button onClick={process} disabled={!file||busy||!text.trim()} className="rounded-lg bg-primary px-5 py-3 font-medium text-primary-foreground disabled:opacity-50">{busy?'Adding watermark…':'Watermark PDF'}</button>{(file||url)&&<button onClick={reset} className="rounded-lg border px-5 py-3 font-medium">Reset</button>}</div>{error&&<p className="mt-4 text-sm text-red-600" role="alert">{error}</p>}{url&&<div className="mt-5 rounded-lg border p-4"><p className="font-medium text-green-700">Watermarked PDF is ready.</p><a href={url} download={file?.name.replace(/\.pdf$/i,'')+'_watermarked.pdf'} className="mt-3 inline-flex rounded-lg border px-5 py-3 font-medium">Download PDF</a></div>}</div></section>
}