import { Metadata } from 'next'
import ToolLandingLayout from '@/components/tool-landing-layout'
import PageNumbersTool from '@/components/tools/page-numbers-tool'

export const metadata: Metadata = {
  title: 'Add Page Numbers to PDF Online | PDFilio',
  description: 'Add sequential page numbers to PDF files online. Choose the starting number, font size, and page number position.',
  keywords: ['add page numbers to PDF','page numbers PDF','number PDF pages','PDF page numbering'],
  alternates:{canonical:'https://pdfilio.com/page-numbers'},
  openGraph:{title:'Add Page Numbers to PDF Online | PDFilio',description:'Add sequential page numbers to every PDF page with position and font-size controls.',url:'https://pdfilio.com/page-numbers',type:'website'},
}
export default function PageNumbersToolPage(){return <><PageNumbersTool/><ToolLandingLayout toolName="Add Page Numbers to PDF" toolSlug="page-numbers" description="Add sequential page numbers to every PDF page and choose where they appear." mainContent="PDFilio adds a new sequential page number to each page of your PDF. Choose the starting number, font size, and one of six page positions. Existing document content stays in place." features={['Sequential page numbering','Six position options','Custom starting number','Adjustable font size','100 MB PDF limit','Separate numbered PDF output']} benefits={['Prepare reports and documents for printing','Make long PDFs easier to navigate','Control numbering position and size','Keep the original PDF unchanged']} relatedTools={[{name:'Edit PDF',slug:'edit-pdf'},{name:'Organize PDF',slug:'organize-pdf'},{name:'Merge PDF',slug:'merge-pdf'},{name:'Compress PDF',slug:'compress-pdf'}]} faqs={[{q:'How do I add page numbers to a PDF?',a:'Upload your PDF, choose the starting number, font size, and position, then select Add Page Numbers.'},{q:'Can I choose where page numbers appear?',a:'Yes. The current tool supports top-left, top-center, top-right, bottom-left, bottom-center, and bottom-right.'},{q:'Can I start numbering from a different number?',a:'Yes. Enter any positive starting number.'},{q:'Will existing PDF content be removed?',a:'No. Page numbers are added as new text over the existing page.'},{q:'What is the PDF upload limit?',a:'The current limit is 100 MB per PDF.'}]} primaryKeyword="add page numbers to PDF" secondaryKeywords={['page numbers PDF','number PDF pages','PDF page numbering']}/></>}
