'use client';

import React, { useRef, useState } from 'react';
import { useFileUpload } from '@/lib/use-file-upload';

interface FileUploadProps { apiEndpoint:string; onSuccess?: (blob:Blob,fileName:string)=>void; onError?: (error:string)=>void; multiple?:boolean; acceptText?:string; placeholder?:string; buttonText?:string; }

export function FileUpload({apiEndpoint,onSuccess,onError,multiple=false,acceptText='PDF files',placeholder='Drag and drop your files here or click to select',buttonText='Choose Files'}:FileUploadProps){
 const inputRef=useRef<HTMLInputElement>(null); const [isDragging,setIsDragging]=useState(false);
 const {isLoading,progress,error,success,fileName,upload,downloadFile,reset}=useFileUpload(apiEndpoint);
 const handleUpload=async(files:FileList|null)=>{if(!files||isLoading)return;await upload(files,{onSuccess:blob=>{const downloadFileName=fileName||'converted-file';downloadFile(blob,downloadFileName);onSuccess?.(blob,fileName);},onError:err=>onError?.(err)})};
 const handleDrop=(e:React.DragEvent)=>{e.preventDefault();setIsDragging(false);handleUpload(e.dataTransfer.files)};
 return <div className="mx-auto w-full max-w-2xl px-1 sm:px-0">
  {!success&&<div role="button" tabIndex={isLoading?-1:0} aria-disabled={isLoading} onKeyDown={e=>{if((e.key==='Enter'||e.key===' ')&&!isLoading){e.preventDefault();inputRef.current?.click()}}} className={`w-full cursor-pointer rounded-xl border-2 border-dashed p-5 text-center transition-all sm:rounded-2xl sm:p-8 lg:p-10 ${isDragging?'border-blue-500 bg-blue-50 shadow-md':'border-gray-300 bg-white hover:border-blue-400 hover:bg-gray-50'} ${isLoading?'cursor-not-allowed opacity-60':''}`} onDragOver={e=>{e.preventDefault();if(!isLoading)setIsDragging(true)}} onDragLeave={()=>setIsDragging(false)} onDrop={handleDrop} onClick={()=>!isLoading&&inputRef.current?.click()}>
   <input ref={inputRef} type="file" onChange={e=>handleUpload(e.currentTarget.files)} multiple={multiple} accept=".pdf" className="sr-only" disabled={isLoading}/>
   <div className="mx-auto flex max-w-lg flex-col items-center gap-4 sm:gap-5"><div className="flex h-14 w-14 items-center justify-center rounded-full bg-blue-50 text-3xl sm:h-16 sm:w-16">📄</div><div className="min-w-0"><p className="break-words text-base font-semibold leading-6 text-gray-800 sm:text-lg">{placeholder}</p><p className="mt-2 break-words text-sm leading-6 text-gray-500">Supports {acceptText}</p></div><button type="button" onClick={e=>{e.stopPropagation();if(!isLoading)inputRef.current?.click()}} disabled={isLoading} className="min-h-12 w-full rounded-lg bg-blue-600 px-5 py-3 text-sm font-bold text-white shadow-sm transition hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:bg-gray-400 sm:w-auto sm:px-7">{isLoading?'Processing...':buttonText}</button></div>
  </div>}
  {isLoading&&<div className="mt-5 rounded-xl border border-gray-200 bg-white p-4 shadow-sm sm:p-5"><div className="mb-2 flex items-center justify-between gap-3"><span className="min-w-0 break-all text-xs font-medium text-gray-700 sm:text-sm">{fileName}</span><span className="shrink-0 text-xs font-bold text-gray-700 sm:text-sm">{progress}%</span></div><div className="h-2.5 w-full overflow-hidden rounded-full bg-gray-200" role="progressbar" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100}><div className="h-full rounded-full bg-blue-600 transition-all duration-300" style={{width:`${progress}%`}}/></div></div>}
  {error&&!success&&<div role="alert" className="mt-5 rounded-xl border border-red-200 bg-red-50 p-4 sm:p-5"><p className="text-sm font-bold text-red-700">Conversion error</p><p className="mt-1 break-words text-sm leading-6 text-red-600">{error}</p><button type="button" onClick={reset} className="mt-3 min-h-10 rounded-md px-2 text-sm font-semibold text-red-700 underline focus:outline-none focus:ring-2 focus:ring-red-500">Try again</button></div>}
  {success&&<div role="status" className="mt-5 rounded-xl border border-green-200 bg-green-50 p-4 sm:p-5"><div className="flex items-start gap-3"><span className="shrink-0 text-2xl">✅</span><div className="min-w-0 flex-1"><p className="text-sm font-bold text-green-700 sm:text-base">File converted successfully!</p><p className="mt-1 break-words text-sm leading-6 text-green-600">{fileName} has been converted and is ready to download.</p><button type="button" onClick={reset} className="mt-3 min-h-10 rounded-md px-2 text-sm font-semibold text-green-700 underline focus:outline-none focus:ring-2 focus:ring-green-500">Convert another file</button></div></div></div>}
 </div>;
}
