'use client';
import Link from 'next/link';
import { FileText, ChevronDown, Menu, X, Moon, Combine, Scissors, RotateCw, Trash2, Layout, Zap, FileUp, Grid3X3, BookOpen, Mail, Lock } from 'lucide-react';
import { useState } from 'react';
interface NavbarProps { onSelectTool?: (toolId: string) => void; onNavigateBlog?: () => void; }
interface DropdownTool { id: string; label: string; description: string; icon: any; color: string; bgColor: string; }
interface Category { label: string; tools: DropdownTool[]; }
export default function Navbar({ onSelectTool = () => {}, onNavigateBlog = () => {} }: NavbarProps) {
  const [openMenu, setOpenMenu] = useState<string | null>(null);
  const [mobileOpen, setMobileOpen] = useState(false);
  const [mobileCategory, setMobileCategory] = useState<string | null>(null);
  const categories: { [key: string]: Category } = {
    organize: { label: 'Organize PDF', tools: [{ id:'merge',label:'Merge PDF',description:'Combine multiple PDF files into one document',icon:Combine,color:'#dc2626',bgColor:'#fee2e2' },{ id:'split',label:'Split PDF',description:'Extract pages from PDF or split into multiple files',icon:Scissors,color:'#ea580c',bgColor:'#ffedd5' },{ id:'rotate',label:'Rotate PDF',description:'Rotate PDF pages to the orientation you need',icon:RotateCw,color:'#ca8a04',bgColor:'#fef3c7' },{ id:'remove-pages',label:'Remove Pages',description:'Delete unwanted pages from your PDF',icon:Trash2,color:'#dc2626',bgColor:'#fee2e2' },{ id:'organize',label:'Organize PDF',description:'Rearrange, delete and rotate PDF pages with ease',icon:Layout,color:'#ec4899',bgColor:'#fce7f3' }] },
    optimize: { label:'Optimize',tools:[{ id:'compress',label:'Compress PDF',description:'Reduce PDF file size while keeping quality',icon:Zap,color:'#16a34a',bgColor:'#dcfce7' }] },
    convert_to: { label:'Convert to PDF',tools:[{ id:'word-to-pdf',label:'Word to PDF',description:'Convert Word documents to PDF format',icon:FileUp,color:'#2563eb',bgColor:'#dbeafe' },{ id:'excel-to-pdf',label:'Excel to PDF',description:'Convert Excel spreadsheets to PDF format',icon:Grid3X3,color:'#16a34a',bgColor:'#dcfce7' },{ id:'ppt-to-pdf',label:'PowerPoint to PDF',description:'Convert PowerPoint presentations to PDF',icon:BookOpen,color:'#ea580c',bgColor:'#ffedd5' },{ id:'jpg-to-pdf',label:'JPG to PDF',description:'Convert images to PDF documents',icon:Mail,color:'#ec4899',bgColor:'#fce7f3' },{ id:'html-to-pdf',label:'HTML to PDF',description:'Convert web pages to PDF documents',icon:Lock,color:'#0891b2',bgColor:'#cffafe' }] },
    convert_from: { label:'Convert from PDF',tools:[{ id:'pdf-to-word',label:'PDF to Word',description:'Convert PDF files to editable Word documents',icon:FileUp,color:'#2563eb',bgColor:'#dbeafe' },{ id:'pdf-to-excel',label:'PDF to Excel',description:'Extract data from PDF to Excel spreadsheets',icon:Grid3X3,color:'#16a34a',bgColor:'#dcfce7' },{ id:'pdf-to-ppt',label:'PDF to PowerPoint',description:'Convert PDF files to editable presentations',icon:BookOpen,color:'#ea580c',bgColor:'#ffedd5' },{ id:'pdf-to-jpg',label:'PDF to JPG',description:'Convert PDF pages to JPG images',icon:Mail,color:'#ec4899',bgColor:'#fce7f3' }] }
  };
  const closeMobile=()=>{setMobileOpen(false);setMobileCategory(null);setOpenMenu(null)};
  const selectTool=(id:string)=>{onSelectTool(id);closeMobile()};
  return <nav className="sticky top-0 z-50 w-full border-b border-gray-200 bg-white shadow-sm">
    <div className="mx-auto w-full max-w-[1600px] px-3 sm:px-5 lg:px-8"><div className="flex min-h-16 items-center justify-between gap-2 py-2">
      <Link href="/" onClick={closeMobile} className="flex min-w-0 shrink-0 items-center gap-2"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-blue-600 shadow-sm"><FileText className="h-5 w-5 text-white"/></div><span className="text-lg font-bold text-gray-900 sm:text-xl">PDFilio</span></Link>
      <div className="hidden min-w-0 flex-1 items-center justify-center gap-1 xl:flex">{Object.entries(categories).map(([key,category])=><div key={key} className="relative" onMouseEnter={()=>setOpenMenu(key)} onMouseLeave={()=>setOpenMenu(null)}><button type="button" className="flex items-center gap-1 whitespace-nowrap rounded px-2 py-2 text-sm font-semibold text-gray-700 transition-colors hover:bg-gray-100 hover:text-gray-900 lg:px-3">{category.label}<ChevronDown className="h-4 w-4"/></button><div className={`absolute left-0 top-full mt-1 w-72 rounded-lg border border-gray-200 bg-white py-3 shadow-2xl transition-all duration-200 ${openMenu===key?'visible opacity-100':'invisible opacity-0'}`}>{category.tools.map(tool=>{const Icon=tool.icon;return <button type="button" key={tool.id} onClick={()=>selectTool(tool.id)} className="flex w-full items-start gap-3 px-5 py-3 text-left transition-colors hover:bg-gray-50"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-gray-100"><Icon className="h-5 w-5 text-gray-700"/></div><div className="min-w-0"><h4 className="text-sm font-semibold text-gray-900">{tool.label}</h4><p className="mt-0.5 text-xs text-gray-600">{tool.description}</p></div></button>})}</div></div>)}<button type="button" onClick={()=>{onNavigateBlog();closeMobile()}} className="rounded px-2 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-100 lg:px-3">Blog</button>{['pricing','about','security','contact','developers'].map((p,i)=><Link key={p} href={`/${p}`} className="whitespace-nowrap rounded px-2 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-100 lg:px-3">{['Pricing','About','Security','Support','API'][i]}</Link>)}</div>
      <div className="hidden shrink-0 items-center gap-1 xl:flex"><button type="button" aria-label="Toggle theme" className="rounded p-2 text-gray-600 hover:bg-gray-100"><Moon className="h-5 w-5"/></button><button type="button" className="rounded px-3 py-2 text-sm font-semibold text-gray-700 hover:bg-gray-100">Sign In</button><button type="button" className="rounded bg-gray-900 px-3 py-2 text-sm font-semibold text-white shadow-sm hover:bg-gray-800">Get Premium</button></div>
      <div className="flex items-center gap-1 xl:hidden"><button type="button" aria-label="Toggle theme" className="rounded-lg p-2 text-gray-600 hover:bg-gray-100"><Moon className="h-5 w-5"/></button><button type="button" aria-label={mobileOpen?'Close menu':'Open menu'} aria-expanded={mobileOpen} onClick={()=>setMobileOpen(v=>!v)} className="rounded-lg p-2 text-gray-700 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-blue-600">{mobileOpen?<X className="h-6 w-6"/>:<Menu className="h-6 w-6"/>}</button></div>
    </div></div>
    {mobileOpen&&<div className="max-h-[calc(100vh-4rem)] overflow-y-auto border-t border-gray-200 bg-white xl:hidden"><div className="mx-auto w-full max-w-2xl px-4 py-4 sm:px-6">{Object.entries(categories).map(([key,category])=><div key={key} className="border-b border-gray-100"><button type="button" onClick={()=>setMobileCategory(mobileCategory===key?null:key)} className="flex min-h-12 w-full items-center justify-between py-3 text-left font-semibold text-gray-800"><span>{category.label}</span><ChevronDown className={`h-5 w-5 transition-transform ${mobileCategory===key?'rotate-180':''}`}/></button>{mobileCategory===key&&<div className="pb-2">{category.tools.map(tool=>{const Icon=tool.icon;return <button type="button" key={tool.id} onClick={()=>selectTool(tool.id)} className="flex min-h-12 w-full items-center gap-3 rounded-lg px-2 py-2 text-left hover:bg-gray-50"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-gray-100"><Icon className="h-4 w-4 text-gray-700"/></div><span className="min-w-0 text-sm font-medium text-gray-800">{tool.label}</span></button>})}</div>}</div>)}<button type="button" onClick={()=>{onNavigateBlog();closeMobile()}} className="min-h-12 w-full border-b border-gray-100 py-3 text-left font-semibold text-gray-800">Blog</button>{['pricing','about','security','contact','developers'].map((p,i)=><Link key={p} href={`/${p}`} onClick={closeMobile} className="flex min-h-12 items-center border-b border-gray-100 font-semibold text-gray-800">{['Pricing','About','Security','Support','API'][i]}</Link>)}<div className="grid grid-cols-2 gap-3 pt-4"><button type="button" className="min-h-12 rounded-lg border border-gray-300 px-4 text-sm font-semibold text-gray-800">Sign In</button><button type="button" className="min-h-12 rounded-lg bg-gray-900 px-4 text-sm font-semibold text-white">Get Premium</button></div></div></div>}
  </nav>;
}
