'use client';

import { ChevronRight, Star, Shield, Zap } from 'lucide-react';
import Link from 'next/link';

interface ToolLandingLayoutProps { toolName:string; toolSlug:string; description:string; features:string[]; benefits:string[]; faqs:Array<{q:string;a:string}>; relatedTools:Array<{name:string;slug:string}>; primaryKeyword:string; secondaryKeywords:string[]; heroImage?:string; useCase?:string; mainContent?:string; howitworks?:string; testimonials?:Array<{name:string;text:string;role?:string}>; schema?:Record<string,any>; }

export default function ToolLandingLayout({toolName,toolSlug,description,features,benefits,faqs,relatedTools,primaryKeyword,secondaryKeywords,heroImage,useCase,mainContent,howitworks,testimonials,schema}:ToolLandingLayoutProps){
 const toolHref=`/${toolSlug}`;
 return <div className="min-h-screen bg-white">
  <nav aria-label="Breadcrumb" className="px-4 sm:px-6 lg:px-8 pt-6"><div className="max-w-5xl mx-auto flex items-center gap-2 text-sm text-gray-600"><Link href="/">Home</Link><ChevronRight className="w-4 h-4" aria-hidden="true"/><Link href="/tools">PDF Tools</Link><ChevronRight className="w-4 h-4" aria-hidden="true"/><span aria-current="page" className="text-gray-900 font-medium">{toolName}</span></div></nav>
  <section className="pt-12 pb-16 px-4 sm:px-6 lg:px-8 bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900"><div className="max-w-5xl mx-auto"><div className="grid grid-cols-1 lg:grid-cols-2 gap-8 items-center"><div><h1 className="text-5xl sm:text-6xl font-black text-white mb-6">{toolName}</h1><p className="text-xl text-gray-300 mb-8 leading-relaxed">{description}</p><Link href={toolHref} className="px-8 py-4 bg-red-600 text-white rounded-lg font-bold inline-flex items-center gap-2">Use {toolName} Now<ChevronRight className="w-5 h-5"/></Link></div>{heroImage&&<div className="hidden lg:block"><img src={heroImage} alt={toolName} className="rounded-lg shadow-2xl"/></div>}</div></div></section>
  {mainContent&&<section className="py-16 px-4 sm:px-6 lg:px-8"><div className="max-w-4xl mx-auto prose prose-lg max-w-none text-gray-700">{mainContent.split('\n').map((p,i)=><p key={i}>{p}</p>)}</div></section>}
  <section className="py-16 px-4 sm:px-6 lg:px-8"><div className="max-w-6xl mx-auto"><h2 className="text-4xl font-black text-gray-900 mb-12 text-center">Key Features</h2><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">{features.map((f,i)=><div key={i} className="bg-gray-50 rounded-lg p-6 border border-gray-200"><div className="flex items-start gap-4"><Star className="w-6 h-6 text-red-600 flex-shrink-0 mt-1"/><h3 className="font-bold text-gray-900">{f}</h3></div></div>)}</div></div></section>
  <section className="py-16 px-4 sm:px-6 lg:px-8 bg-gray-50"><div className="max-w-6xl mx-auto"><h2 className="text-4xl font-black text-gray-900 mb-12 text-center">Benefits</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-8">{benefits.map((b,i)=><div key={i} className="flex items-start gap-4"><Shield className="w-6 h-6 text-red-600 flex-shrink-0 mt-1"/><h3 className="font-bold text-gray-900">{b}</h3></div>)}</div></div></section>
  {useCase&&<section className="py-16 px-4 sm:px-6 lg:px-8 bg-blue-50"><div className="max-w-4xl mx-auto"><h2 className="text-3xl font-black text-gray-900 mb-6">Use Cases</h2>{useCase.split('\n').map((x,i)=><p key={i} className="mb-3 text-gray-700">{x}</p>)}</div></section>}
  {testimonials&&testimonials.length>0&&<section className="py-16 px-4 sm:px-6 lg:px-8 bg-gray-50"><div className="max-w-6xl mx-auto"><h2 className="text-4xl font-black text-gray-900 mb-12 text-center">What Users Say</h2><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{testimonials.map((t,i)=><div key={i} className="bg-white rounded-lg p-6 border border-gray-200"><p className="text-gray-600 mb-4 italic">&quot;{t.text}&quot;</p><p className="font-bold text-gray-900">{t.name}</p>{t.role&&<p className="text-sm text-gray-500">{t.role}</p>}</div>)}</div></div></section>}
  <section className="py-16 px-4 sm:px-6 lg:px-8"><div className="max-w-4xl mx-auto"><h2 className="text-4xl font-black text-gray-900 mb-12 text-center">How to Use {toolName}</h2><div className="space-y-6"><div><h3 className="font-bold text-gray-900 mb-2">1. Upload Your File</h3><p className="text-gray-600">Choose your PDF file.</p></div><div><h3 className="font-bold text-gray-900 mb-2">2. Configure Settings</h3><p className="text-gray-600">Choose the available options.</p></div><div><h3 className="font-bold text-gray-900 mb-2">3. Download Result</h3><p className="text-gray-600">Download the result when it is ready.</p></div></div></div></section>
  <section className="py-16 px-4 sm:px-6 lg:px-8 bg-gray-50"><div className="max-w-4xl mx-auto"><h2 className="text-4xl font-black text-gray-900 mb-12 text-center">Frequently Asked Questions</h2><div className="space-y-6">{faqs.map((f,i)=><div key={i} className="bg-white rounded-lg p-6 border border-gray-200"><h3 className="font-bold text-gray-900 mb-3 flex items-center gap-2"><Zap className="w-5 h-5 text-red-600"/>{f.q}</h3><p className="text-gray-600">{f.a}</p></div>)}</div></div></section>
  <section className="py-16 px-4 sm:px-6 lg:px-8"><div className="max-w-6xl mx-auto"><h2 className="text-4xl font-black text-gray-900 mb-12 text-center">Related Tools</h2><div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">{relatedTools.map((t,i)=><Link key={i} href={`/${t.slug}`} className="p-6 bg-gray-50 rounded-lg border border-gray-200"><h3 className="font-bold text-gray-900">{t.name}</h3><p className="text-sm text-gray-600">Learn more<ChevronRight className="w-4 h-4 inline"/></p></Link>)}</div></div></section>
  <section className="py-16 px-4 sm:px-6 lg:px-8 bg-gradient-to-r from-red-600 to-red-700"><div className="max-w-4xl mx-auto text-center"><h2 className="text-4xl font-black text-white mb-6">Start {toolName} Now</h2><p className="text-xl text-red-100 mb-8">Use the tool directly and download your result when it is ready.</p><Link href={toolHref} className="px-8 py-4 bg-white text-red-600 rounded-lg font-bold inline-flex items-center gap-2">Use {toolName}<ChevronRight className="w-5 h-5"/></Link></div></section>
  {schema&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>}
  {!schema&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'SoftwareApplication',name:toolName,description,applicationCategory:'Utility',offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}})}}/>}
 </div>;
}
