'use client';

import { ChevronRight, Star, Shield, Zap } from 'lucide-react';
import Link from 'next/link';

interface ToolLandingLayoutProps { toolName:string; toolSlug:string; description:string; features:string[]; benefits:string[]; faqs:Array<{q:string;a:string}>; relatedTools:Array<{name:string;slug:string}>; primaryKeyword:string; secondaryKeywords:string[]; heroImage?:string; useCase?:string; mainContent?:string; howitworks?:string; testimonials?:Array<{name:string;text:string;role?:string}>; schema?:Record<string,any>; }

export default function ToolLandingLayout({toolName,toolSlug,description,features,benefits,faqs,relatedTools,primaryKeyword,secondaryKeywords,heroImage,useCase,mainContent,howitworks,testimonials,schema}:ToolLandingLayoutProps){
 const toolHref=`/${toolSlug}`;
 return <div className="min-h-screen w-full overflow-x-hidden bg-white">
  <nav aria-label="Breadcrumb" className="px-3 pt-4 sm:px-6 sm:pt-6 lg:px-8"><div className="mx-auto flex w-full max-w-5xl flex-wrap items-center gap-1.5 text-xs text-gray-600 sm:gap-2 sm:text-sm"><Link href="/">Home</Link><ChevronRight className="h-3.5 w-3.5 shrink-0 sm:h-4 sm:w-4" aria-hidden="true"/><Link href="/tools">PDF Tools</Link><ChevronRight className="h-3.5 w-3.5 shrink-0 sm:h-4 sm:w-4" aria-hidden="true"/><span aria-current="page" className="min-w-0 break-words font-medium text-gray-900">{toolName}</span></div></nav>
  <section className="bg-gradient-to-br from-slate-900 via-slate-800 to-slate-900 px-4 py-10 sm:px-6 sm:py-14 lg:px-8 lg:py-16"><div className="mx-auto w-full max-w-6xl"><div className="grid grid-cols-1 items-center gap-8 lg:grid-cols-2 lg:gap-12"><div className="min-w-0"><h1 className="text-3xl font-black leading-tight text-white sm:text-5xl lg:text-6xl">{toolName}</h1><p className="mt-4 text-base leading-7 text-gray-300 sm:mt-6 sm:text-xl sm:leading-relaxed">{description}</p><Link href={toolHref} className="mt-6 inline-flex min-h-12 max-w-full items-center justify-center gap-2 rounded-lg bg-red-600 px-5 py-3 text-center font-bold text-white transition hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-slate-900 sm:mt-8 sm:px-8 sm:py-4">Use {toolName} Now<ChevronRight className="h-5 w-5 shrink-0"/></Link></div>{heroImage&&<div className="hidden min-w-0 lg:block"><img src={heroImage} alt={toolName} loading="eager" className="h-auto w-full rounded-lg object-cover shadow-2xl"/></div>}</div></div></section>
  {mainContent&&<section className="px-4 py-10 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto w-full max-w-4xl text-base leading-7 text-gray-700 sm:text-lg sm:leading-8">{mainContent.split('\\n').map((p,i)=><p key={i} className="mb-5 last:mb-0">{p}</p>)}</div></section>}
  <section className="px-4 py-10 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto w-full max-w-6xl"><h2 className="mb-8 text-center text-2xl font-black text-gray-900 sm:mb-12 sm:text-4xl">Key Features</h2><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 sm:gap-6 lg:grid-cols-3 lg:gap-8">{features.map((f,i)=><div key={i} className="min-w-0 rounded-lg border border-gray-200 bg-gray-50 p-4 sm:p-6"><div className="flex items-start gap-3 sm:gap-4"><Star className="mt-1 h-5 w-5 shrink-0 text-red-600 sm:h-6 sm:w-6"/><h3 className="min-w-0 break-words font-bold text-gray-900">{f}</h3></div></div>)}</div></div></section>
  <section className="bg-gray-50 px-4 py-10 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto w-full max-w-6xl"><h2 className="mb-8 text-center text-2xl font-black text-gray-900 sm:mb-12 sm:text-4xl">Benefits</h2><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 sm:gap-8">{benefits.map((b,i)=><div key={i} className="flex min-w-0 items-start gap-3 sm:gap-4"><Shield className="mt-1 h-5 w-5 shrink-0 text-red-600 sm:h-6 sm:w-6"/><h3 className="min-w-0 break-words font-bold text-gray-900">{b}</h3></div>)}</div></div></section>
  {useCase&&<section className="bg-blue-50 px-4 py-10 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto w-full max-w-4xl"><h2 className="mb-5 text-2xl font-black text-gray-900 sm:mb-6 sm:text-3xl">Use Cases</h2>{useCase.split('\\n').map((x,i)=><p key={i} className="mb-3 break-words text-base leading-7 text-gray-700 sm:text-lg">{x}</p>)}</div></section>}
  {testimonials&&testimonials.length>0&&<section className="bg-gray-50 px-4 py-10 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto w-full max-w-6xl"><h2 className="mb-8 text-center text-2xl font-black text-gray-900 sm:mb-12 sm:text-4xl">What Users Say</h2><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 lg:grid-cols-3 lg:gap-6">{testimonials.map((t,i)=><div key={i} className="min-w-0 rounded-lg border border-gray-200 bg-white p-5 sm:p-6"><p className="mb-4 break-words text-gray-600 italic">&quot;{t.text}&quot;</p><p className="break-words font-bold text-gray-900">{t.name}</p>{t.role&&<p className="break-words text-sm text-gray-500">{t.role}</p>}</div>)}</div></div></section>}
  <section className="px-4 py-10 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto w-full max-w-4xl"><h2 className="mb-8 text-center text-2xl font-black text-gray-900 sm:mb-12 sm:text-4xl">How to Use {toolName}</h2><div className="space-y-5 sm:space-y-6"><div><h3 className="mb-2 font-bold text-gray-900">1. Upload Your File</h3><p className="text-gray-600">Choose your PDF file.</p></div><div><h3 className="mb-2 font-bold text-gray-900">2. Configure Settings</h3><p className="text-gray-600">Choose the available options.</p></div><div><h3 className="mb-2 font-bold text-gray-900">3. Download Result</h3><p className="text-gray-600">Download the result when it is ready.</p></div></div></div></section>
  <section className="bg-gray-50 px-4 py-10 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto w-full max-w-4xl"><h2 className="mb-8 text-center text-2xl font-black text-gray-900 sm:mb-12 sm:text-4xl">Frequently Asked Questions</h2><div className="space-y-4 sm:space-y-6">{faqs.map((f,i)=><div key={i} className="min-w-0 rounded-lg border border-gray-200 bg-white p-4 sm:p-6"><h3 className="flex items-start gap-2 break-words font-bold leading-6 text-gray-900"><Zap className="mt-0.5 h-5 w-5 shrink-0 text-red-600"/>{f.q}</h3><p className="mt-3 break-words leading-7 text-gray-600">{f.a}</p></div>)}</div></div></section>
  <section className="px-4 py-10 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto w-full max-w-6xl"><h2 className="mb-8 text-center text-2xl font-black text-gray-900 sm:mb-12 sm:text-4xl">Related Tools</h2><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 sm:gap-6 lg:grid-cols-3">{relatedTools.map((t,i)=><Link key={i} href={`/${t.slug}`} className="min-w-0 rounded-lg border border-gray-200 bg-gray-50 p-5 transition hover:border-gray-300 sm:p-6"><h3 className="break-words font-bold text-gray-900">{t.name}</h3><p className="mt-1 text-sm text-gray-600">Learn more<ChevronRight className="inline h-4 w-4"/></p></Link>)}</div></div></section>
  <section className="bg-gradient-to-r from-red-600 to-red-700 px-4 py-10 sm:px-6 sm:py-16 lg:px-8"><div className="mx-auto w-full max-w-4xl text-center"><h2 className="text-2xl font-black text-white sm:text-4xl">Start {toolName} Now</h2><p className="mt-4 text-base leading-7 text-red-100 sm:mb-8 sm:text-xl">Use the tool directly and download your result when it is ready.</p><Link href={toolHref} className="mt-6 inline-flex min-h-12 max-w-full items-center justify-center gap-2 rounded-lg bg-white px-5 py-3 text-center font-bold text-red-600 sm:px-8 sm:py-4">Use {toolName}<ChevronRight className="h-5 w-5 shrink-0"/></Link></div></section>
  {schema&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>}
  {!schema&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({'@context':'https://schema.org','@type':'SoftwareApplication',name:toolName,description,applicationCategory:'Utility',offers:{'@type':'Offer',price:'0',priceCurrency:'USD'}})}}/>}
 </div>;
}
