export type Language = 'en' | 'es' | 'fr' | 'de' | 'it' | 'pt' | 'ru' | 'ja' | 'zh' | 'ar' | 'hi' | 'ko';

export const languages: Record<Language, { name: string; nativeName: string; flag: string }> = {
  en: { name: 'English', nativeName: 'English', flag: '🇺🇸' },
  es: { name: 'Spanish', nativeName: 'Español', flag: '🇪🇸' },
  fr: { name: 'French', nativeName: 'Français', flag: '🇫🇷' },
  de: { name: 'German', nativeName: 'Deutsch', flag: '🇩🇪' },
  it: { name: 'Italian', nativeName: 'Italiano', flag: '🇮🇹' },
  pt: { name: 'Portuguese', nativeName: 'Português', flag: '🇵🇹' },
  ru: { name: 'Russian', nativeName: 'Русский', flag: '🇷🇺' },
  ja: { name: 'Japanese', nativeName: '日本語', flag: '🇯🇵' },
  zh: { name: 'Chinese', nativeName: '中文', flag: '🇨🇳' },
  ar: { name: 'Arabic', nativeName: 'العربية', flag: '🇸🇦' },
  hi: { name: 'Hindi', nativeName: 'हिन्दी', flag: '🇮🇳' },
  ko: { name: 'Korean', nativeName: '한국어', flag: '🇰🇷' }
};

export const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.blog': 'Blog',
    'nav.pricing': 'Pricing',
    'nav.about': 'About',
    'nav.security': 'Security',
    'nav.support': 'Support',
    'nav.api': 'API',
    'hero.title': 'Your Complete PDF Toolkit',
    'hero.subtitle': 'AI-powered PDF workspace for professionals',
    'hero.cta': 'Get Started Free',
    'footer.copyright': '© 2024 PDFilio. All rights reserved.',
  },
  es: {
    'nav.home': 'Inicio',
    'nav.blog': 'Blog',
    'nav.pricing': 'Precios',
    'nav.about': 'Acerca de',
    'nav.security': 'Seguridad',
    'nav.support': 'Soporte',
    'nav.api': 'API',
    'hero.title': 'Tu Kit Completo de PDF',
    'hero.subtitle': 'Espacio de trabajo PDF impulsado por IA para profesionales',
    'hero.cta': 'Comenzar Gratis',
    'footer.copyright': '© 2024 PDFilio. Todos los derechos reservados.',
  },
  fr: {
    'nav.home': 'Accueil',
    'nav.blog': 'Blog',
    'nav.pricing': 'Tarification',
    'nav.about': 'À propos',
    'nav.security': 'Sécurité',
    'nav.support': 'Support',
    'nav.api': 'API',
    'hero.title': 'Votre Suite PDF Complète',
    'hero.subtitle': 'Espace de travail PDF alimenté par l\'IA pour les professionnels',
    'hero.cta': 'Commencer Gratuitement',
    'footer.copyright': '© 2024 PDFilio. Tous droits réservés.',
  },
  de: {
    'nav.home': 'Startseite',
    'nav.blog': 'Blog',
    'nav.pricing': 'Preisgestaltung',
    'nav.about': 'Über Uns',
    'nav.security': 'Sicherheit',
    'nav.support': 'Unterstützung',
    'nav.api': 'API',
    'hero.title': 'Ihr Komplettes PDF-Toolkit',
    'hero.subtitle': 'KI-betriebener PDF-Arbeitsbereich für Fachleute',
    'hero.cta': 'Kostenlos Beginnen',
    'footer.copyright': '© 2024 PDFilio. Alle Rechte vorbehalten.',
  },
  it: {
    'nav.home': 'Home',
    'nav.blog': 'Blog',
    'nav.pricing': 'Prezzi',
    'nav.about': 'Chi Siamo',
    'nav.security': 'Sicurezza',
    'nav.support': 'Supporto',
    'nav.api': 'API',
    'hero.title': 'Il Tuo Toolkit PDF Completo',
    'hero.subtitle': 'Spazio di lavoro PDF alimentato da IA per professionisti',
    'hero.cta': 'Inizia Gratis',
    'footer.copyright': '© 2024 PDFilio. Tutti i diritti riservati.',
  },
  pt: {
    'nav.home': 'Início',
    'nav.blog': 'Blog',
    'nav.pricing': 'Preços',
    'nav.about': 'Sobre',
    'nav.security': 'Segurança',
    'nav.support': 'Suporte',
    'nav.api': 'API',
    'hero.title': 'Seu Kit Completo de PDF',
    'hero.subtitle': 'Espaço de trabalho PDF alimentado por IA para profissionais',
    'hero.cta': 'Começar Grátis',
    'footer.copyright': '© 2024 PDFilio. Todos os direitos reservados.',
  },
  ru: {
    'nav.home': 'Главная',
    'nav.blog': 'Блог',
    'nav.pricing': 'Цены',
    'nav.about': 'О нас',
    'nav.security': 'Безопасность',
    'nav.support': 'Поддержка',
    'nav.api': 'API',
    'hero.title': 'Ваш Полный PDF Набор',
    'hero.subtitle': 'Рабочее пространство PDF на основе ИИ для профессионалов',
    'hero.cta': 'Начать Бесплатно',
    'footer.copyright': '© 2024 PDFilio. Все права защищены.',
  },
  ja: {
    'nav.home': 'ホーム',
    'nav.blog': 'ブログ',
    'nav.pricing': '価格',
    'nav.about': 'について',
    'nav.security': 'セキュリティ',
    'nav.support': 'サポート',
    'nav.api': 'API',
    'hero.title': 'あなたの完全なPDFツールキット',
    'hero.subtitle': 'プロフェッショナル向けAIパワーPDFワークスペース',
    'hero.cta': '無料で開始',
    'footer.copyright': '© 2024 PDFilio. すべての権利を保有します。',
  },
  zh: {
    'nav.home': '首页',
    'nav.blog': '博客',
    'nav.pricing': '定价',
    'nav.about': '关于',
    'nav.security': '安全',
    'nav.support': '支持',
    'nav.api': 'API',
    'hero.title': '您完整的PDF工具包',
    'hero.subtitle': '面向专业人士的AI驱动PDF工作区',
    'hero.cta': '免费开始',
    'footer.copyright': '© 2024 PDFilio. 版权所有。',
  },
  ar: {
    'nav.home': 'الرئيسية',
    'nav.blog': 'المدونة',
    'nav.pricing': 'التسعير',
    'nav.about': 'حول',
    'nav.security': 'الأمان',
    'nav.support': 'الدعم',
    'nav.api': 'API',
    'hero.title': 'مجموعة PDF الكاملة الخاصة بك',
    'hero.subtitle': 'مساحة عمل PDF مدعومة بالذكاء الاصطناعي للمحترفين',
    'hero.cta': 'ابدأ مجانًا',
    'footer.copyright': '© 2024 PDFilio. جميع الحقوق محفوظة.',
  },
  hi: {
    'nav.home': 'होम',
    'nav.blog': 'ब्लॉग',
    'nav.pricing': 'मूल्य निर्धारण',
    'nav.about': 'परिचय',
    'nav.security': 'सुरक्षा',
    'nav.support': 'सहायता',
    'nav.api': 'API',
    'hero.title': 'आपकी संपूर्ण PDF टूलकिट',
    'hero.subtitle': 'पेशेवारों के लिए AI-संचालित PDF कार्यक्षेत्र',
    'hero.cta': 'मुफ्त शुरू करें',
    'footer.copyright': '© 2024 PDFilio. सर्वाधिकार सुरक्षित।',
  },
  ko: {
    'nav.home': '홈',
    'nav.blog': '블로그',
    'nav.pricing': '가격',
    'nav.about': '소개',
    'nav.security': '보안',
    'nav.support': '지원',
    'nav.api': 'API',
    'hero.title': '당신의 완전한 PDF 도구 모음',
    'hero.subtitle': '전문가를 위한 AI 기반 PDF 작업 영역',
    'hero.cta': '무료로 시작',
    'footer.copyright': '© 2024 PDFilio. 판권 소유.',
  },
};
