import {
  Merge,
  Scissors,
  RotateCw,
  Trash2,
  Grid3x3,
  Zap,
  FileText,
  Table,
  Presentation,
  Image,
  Code,
  FileDown,
  FileUp,
  Edit3,
  Stamp,
  Hash,
  Eye,
  Crop,
  Lock,
  Unlock,
  PenTool,
  Wrench,
  MessageCircle,
  FileCheck,
  Globe,
  Scan,
  Award,
  Shield,
  DollarSign,
  BookOpen,
  HelpCircle,
  Settings,
  Briefcase,
  Search,
} from 'lucide-react';

export interface Tool {
  id: string;
  name: string;
  description: string;
  category: string;
  icon: any;
  color: string;
  badge?: string;
}

export const tools: Tool[] = [
  // Organize PDF
  {
    id: 'merge',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one document',
    category: 'organize',
    icon: Merge,
    color: '#cc0000',
  },
  {
    id: 'split',
    name: 'Split PDF',
    description: 'Extract pages from PDF or split into multiple files',
    category: 'organize',
    icon: Scissors,
    color: '#cc0000',
  },
  {
    id: 'rotate',
    name: 'Rotate PDF',
    description: 'Rotate PDF pages to the orientation you need',
    category: 'organize',
    icon: RotateCw,
    color: '#cc0000',
  },
  {
    id: 'remove-pages',
    name: 'Remove Pages',
    description: 'Delete unwanted pages from your PDF',
    category: 'organize',
    icon: Trash2,
    color: '#cc0000',
  },
  {
    id: 'organize',
    name: 'Organize PDF',
    description: 'Rearrange, delete and rotate PDF pages with ease',
    category: 'organize',
    icon: Grid3x3,
    color: '#cc0000',
  },

  // Optimize
  {
    id: 'compress',
    name: 'Compress PDF',
    description: 'Reduce file size while maintaining quality',
    category: 'optimize',
    icon: Zap,
    color: '#ff9900',
  },

  // Convert to PDF
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert Word documents to PDF format',
    category: 'convert_to',
    icon: FileText,
    color: '#0066cc',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF',
    category: 'convert_to',
    icon: Table,
    color: '#0066cc',
  },
  {
    id: 'ppt-to-pdf',
    name: 'PowerPoint to PDF',
    description: 'Convert PowerPoint presentations to PDF',
    category: 'convert_to',
    icon: Presentation,
    color: '#0066cc',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert images to PDF documents',
    category: 'convert_to',
    icon: Image,
    color: '#0066cc',
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert web pages to PDF',
    category: 'convert_to',
    icon: Code,
    color: '#0066cc',
  },

  // Convert from PDF
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Extract text from PDF to editable Word documents',
    category: 'convert_from',
    icon: FileDown,
    color: '#00aa00',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Extract data from PDF to Excel spreadsheets',
    category: 'convert_from',
    icon: FileDown,
    color: '#00aa00',
  },
  {
    id: 'pdf-to-ppt',
    name: 'PDF to PowerPoint',
    description: 'Convert PDF to editable presentations',
    category: 'convert_from',
    icon: FileDown,
    color: '#00aa00',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert PDF pages to JPG images',
    category: 'convert_from',
    icon: FileDown,
    color: '#00aa00',
  },
  {
    id: 'pdf-to-png',
    name: 'PDF to PNG',
    description: 'Convert PDF pages to PNG images',
    category: 'convert_from',
    icon: FileDown,
    color: '#00aa00',
  },

  // Edit & Manage
  {
    id: 'edit-pdf',
    name: 'Edit PDF',
    description: 'Add text, images, shapes to your PDF',
    category: 'edit',
    icon: Edit3,
    color: '#9933cc',
  },
  {
    id: 'watermark',
    name: 'Watermark PDF',
    description: 'Stamp an image or text on your PDF',
    category: 'edit',
    icon: Stamp,
    color: '#9933cc',
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    description: 'Add page numbers to your PDF document',
    category: 'edit',
    icon: Hash,
    color: '#9933cc',
  },
  {
    id: 'redact',
    name: 'Redact PDF',
    description: 'Redact text and graphics to permanently remove',
    category: 'edit',
    icon: Eye,
    color: '#9933cc',
  },
  {
    id: 'crop',
    name: 'Crop PDF',
    description: 'Remove margins and crop PDF pages to exact size',
    category: 'edit',
    icon: Crop,
    color: '#9933cc',
  },
  {
    id: 'protect',
    name: 'Protect PDF',
    description: 'Encrypt PDF with a password',
    category: 'edit',
    icon: Lock,
    color: '#9933cc',
  },
  {
    id: 'unlock',
    name: 'Unlock PDF',
    description: 'Remove password from protected PDF',
    category: 'edit',
    icon: Unlock,
    color: '#9933cc',
  },
  {
    id: 'sign',
    name: 'Sign PDF',
    description: 'Add your signature to PDF documents',
    category: 'edit',
    icon: PenTool,
    color: '#9933cc',
  },

  // AI Features
  {
    id: 'chat-pdf',
    name: 'Chat With PDF',
    description: 'Ask questions about your documents with AI',
    category: 'ai',
    icon: MessageCircle,
    color: '#cc00cc',
    badge: 'NEW',
  },
  {
    id: 'summarize',
    name: 'AI PDF Summarizer',
    description: 'Generate comprehensive document summaries with AI',
    category: 'ai',
    icon: FileCheck,
    color: '#cc00cc',
    badge: 'NEW',
  },
  {
    id: 'translate',
    name: 'AI Translator',
    description: 'Translate entire PDF to 10+ languages instantly',
    category: 'ai',
    icon: Globe,
    color: '#cc00cc',
    badge: 'NEW',
  },
  {
    id: 'research-assistant',
    name: 'AI Research Assistant',
    description: 'Extract insights and generate research summaries',
    category: 'ai',
    icon: Search,
    color: '#cc00cc',
    badge: 'NEW',
  },
  {
    id: 'ocr',
    name: 'OCR Text',
    description: 'Extract text from scanned PDFs and images',
    category: 'ai',
    icon: Scan,
    color: '#cc00cc',
    badge: 'NEW',
  },
  {
    id: 'resume-analyzer',
    name: 'AI Resume Analyzer',
    description: 'Professional resume scoring & feedback',
    category: 'ai',
    icon: Award,
    color: '#cc00cc',
    badge: 'NEW',
  },
  {
    id: 'contract-analyzer',
    name: 'AI Contract Analyzer',
    description: 'Extract clauses, analyze risks, and understand contracts',
    category: 'ai',
    icon: Shield,
    color: '#cc00cc',
    badge: 'NEW',
  },
  {
    id: 'invoice-generator',
    name: 'AI Invoice Generator',
    description: 'Create professional invoices instantly',
    category: 'ai',
    icon: DollarSign,
    color: '#cc00cc',
    badge: 'NEW',
  },
  {
    id: 'cover-letter',
    name: 'AI Cover Letter Generator',
    description: 'Generate personalized cover letters instantly',
    category: 'ai',
    icon: FileText,
    color: '#cc00cc',
    badge: 'NEW',
  },
  {
    id: 'business-proposal',
    name: 'AI Business Proposal',
    description: 'Create professional business proposals quickly',
    category: 'ai',
    icon: Briefcase,
    color: '#cc00cc',
    badge: 'NEW',
  },
  {
    id: 'study-notes',
    name: 'AI Notes Generator',
    description: 'Convert PDFs into organized study notes automatically',
    category: 'ai',
    icon: BookOpen,
    color: '#cc00cc',
    badge: 'NEW',
  },
  {
    id: 'quiz-generator',
    name: 'AI Quiz Generator',
    description: 'Create multiple choice questions from PDFs automatically',
    category: 'ai',
    icon: HelpCircle,
    color: '#cc00cc',
    badge: 'NEW',
  },
  {
    id: 'metadata',
    name: 'PDF Metadata Editor',
    description: 'Edit PDF title, author, and keywords',
    category: 'ai',
    icon: Settings,
    color: '#cc00cc',
  },
];

export const toolsByCategory = {
  organize: tools.filter(t => t.category === 'organize'),
  optimize: tools.filter(t => t.category === 'optimize'),
  convert_to: tools.filter(t => t.category === 'convert_to'),
  convert_from: tools.filter(t => t.category === 'convert_from'),
  edit: tools.filter(t => t.category === 'edit'),
  ai: tools.filter(t => t.category === 'ai'),
};
