import { ToolLandingLayout } from '@/components/tool-landing-layout';
export const metadata = { title: 'AI Quiz Generator | PDFilio', description: 'Generate quiz questions from documents with AI. Create study materials and assessments instantly.' };
export default function Page() {
  const schema = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'AI Quiz Generator', description: 'AI-powered quiz question generation', applicationCategory: 'Utility', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, aggregateRating: { '@type': 'AggregateRating', ratingValue: '4.8', ratingCount: '1900' } };
  return (<ToolLandingLayout toolName="AI Quiz Generator" toolSlug="ai-quiz-generator" description="Create quiz questions automatically from any document. Generate study materials, assessments, and learning tools." heroImage="/tool-images/ai-quiz-generator-hero.png" mainContent={`AI Quiz Generator automatically creates quiz questions from your documents. Perfect for teachers, trainers, and students preparing for exams. Generate multiple choice, true/false, and essay questions instantly.

Our AI extracts key concepts and creates meaningful questions. Include answer keys and difficulty levels. Customizable question types and formats.

Upload any document and generate instant quiz questions. Create practice tests, study materials, or formal assessments. Export as printable PDF or online quiz format.`} useCase={`Educational material creation\nExam preparation\nStudent assessment\nTraining evaluation\nKnowledge testing\nStudy material generation\nOnline course development\nLearning reinforcement`} testimonials={[{name: 'Patricia Russo', role: 'Teacher', text: 'AI Quiz Generator saves hours on test creation. Creates comprehensive quizzes from course materials instantly!'},{name: 'Michael Chen', role: 'Corporate Trainer', text: 'Perfect for training assessment. Generates relevant quiz questions automatically.'},{name: 'Sophie Anderson', role: 'Student', text: 'Use it for exam prep. Creates great practice questions from study materials.'}]} features={['Question generation','Multiple formats','Difficulty levels','Answer keys','Customizable','Batch generation','Export options','Assessment creation']} benefits={['Save time','Create assessments faster','Test knowledge','Better learning','Multiple question types','Quality questions','Easy to customize','Instant generation']} faqs={[{q: 'Question types?', a: 'Multiple choice, true/false, short answer, and essay questions generated.'},{q: 'Difficulty levels?', a: 'Yes! Easy, medium, and hard questions for comprehensive testing.'},{q: 'Answer keys?', a: 'Yes! Complete answer keys included for all questions."},{q: 'Export?', a: 'PDF for printing or online quiz platform formats.'},{q: 'Customizable?', a: 'Absolutely! Edit questions, add hints, adjust difficulty.'},{q: 'Multiple documents?', a: 'Yes! Generate quizzes from multiple source documents.'},{q: 'Academic subjects?', a: 'Works with any subject: science, history, languages, math, etc.'},{q: 'Accuracy?', a: 'Professional-grade questions based on document content.'},{q: 'Is it free?', a: 'Completely free with unlimited quiz generation.'},{q: 'Best for teachers?', a: 'Perfect! Saves hours on test creation and assessment development.'}]} relatedTools={[{name: 'AI Notes Generator', slug: 'ai-notes-generator'},{name: 'AI PDF Summary', slug: 'ai-pdf-summary'},{name: 'AI Chat PDF', slug: 'ai-chat-pdf'}]} schema={schema} primaryKeyword="AI quiz generator" secondaryKeywords={['quiz maker', 'question generator', 'test creator']} />);
}
