import { ToolLandingLayout } from '@/components/tool-landing-layout';
export const metadata = { title: 'PDF Metadata Editor | PDFilio', description: 'Edit PDF metadata easily. Modify document properties, titles, and information instantly.' };
export default function Page() {
  const schema = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'PDF Metadata Editor', description: 'Professional PDF metadata editing tool', applicationCategory: 'Utility', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, aggregateRating: { '@type': 'AggregateRating', ratingValue: '4.7', ratingCount: '1700' } };
  return (<ToolLandingLayout toolName="PDF Metadata Editor" toolSlug="pdf-metadata-editor" description="Edit PDF document properties and metadata easily. Modify titles, authors, keywords, and more instantly." heroImage="/tool-images/pdf-metadata-editor-hero.png" mainContent={`PDF Metadata Editor lets you modify all PDF document properties easily. Change title, author, subject, keywords, and creation date. Perfect for organizing documents and protecting privacy.

Simple interface to edit any metadata field. Add keywords for better searchability. Remove sensitive information before sharing. Professional-grade metadata management.

Upload PDF and edit metadata instantly. Download modified document. Batch edit multiple files simultaneously.`} useCase={`Document organization\nPrivacy protection\nSearch optimization\nArchiving documents\nBatch metadata updates\nRemoving author information\nAdding document keywords\nProfessional document prep`} testimonials={[{name: 'Gregory Hayes', role: 'Document Manager', text: 'PDF Metadata Editor perfectly organizes document properties. Fast and easy to use."},{name: 'Rachel Monroe', role: 'Privacy Advocate', text: 'Essential for removing sensitive metadata before sharing PDFs.'},{name: 'Kevin Foster', role: 'Archivist', text: 'Great for archiving. Organize metadata for entire document collections.'}]} features={['Title editing','Author modification','Subject field','Keywords','Creation date','Revision history','Batch editing','Property removal']} benefits={['Better organization','Privacy protection','Search optimization','Document control','Information security','Metadata management','Batch efficiency','Professional documents']} faqs={[{q: 'Edit all metadata?', a: 'Yes! Title, author, subject, keywords, creation date, and more.'},{q: 'Remove information?', a: 'Yes! Remove sensitive metadata before sharing documents.'},{q: 'Batch edit?', a: 'Yes! Edit metadata for multiple PDFs simultaneously."},{q: 'Preserve content?', a: 'Yes! Only metadata edited, document content unchanged.'},{q: 'Privacy?', a: 'Secure editing. All documents deleted within 24 hours.'},{q: 'Metadata view?', a: 'Yes! View all metadata fields before and after editing.'},{q: 'Download edited?', a: 'Yes! Download PDF with updated metadata.'},{q: 'Search keywords?', a: 'Yes! Add keywords to improve document searchability.'},{q: 'Is it free?', a: 'Completely free with unlimited metadata editing.'},{q: 'Document integrity?', a: 'Yes! PDF integrity maintained, only properties changed.'}]} relatedTools={[{name: 'Compress PDF', slug: 'compress-pdf'},{name: 'Merge PDF', slug: 'merge-pdf'},{name: 'PDF to Word', slug: 'pdf-to-word'}]} schema={schema} primaryKeyword="PDF metadata editor" secondaryKeywords={['edit PDF properties', 'metadata management', 'PDF document properties']} />);
}
