import { ToolLandingLayout } from '@/components/tool-landing-layout';
export const metadata = { title: 'Batch Conversion | PDFilio', description: 'Convert multiple files at once with batch processing. Save time on bulk file conversions instantly.' };
export default function Page() {
  const schema = { '@context': 'https://schema.org', '@type': 'SoftwareApplication', name: 'Batch Conversion', description: 'Professional batch file conversion tool', applicationCategory: 'Utility', offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }, aggregateRating: { '@type': 'AggregateRating', ratingValue: '4.8', ratingCount: '2100' } };
  return (<ToolLandingLayout toolName="Batch Conversion" toolSlug="batch-conversion" description="Convert multiple files simultaneously. Process hundreds of documents in batch for maximum efficiency." heroImage="/tool-images/batch-conversion-hero.png" mainContent={`Batch Conversion lets you process multiple files simultaneously. Convert hundreds of PDFs, Word documents, or images at once. Save hours on repetitive conversion tasks.

Upload any number of files and select target format. Process all files automatically with one click. Download all converted files together. Perfect for large-scale document processing.

Supports PDF, Word, Excel, Images, PowerPoint conversions. Maintain formatting and quality. Download processed files as ZIP archive.`} useCase={`Large document migrations\nBulk format conversion\nArchive processing\nDocument standardization\nMulti-document prep\nFolder digitization\nFormat standardization\nWorkflow automation`} testimonials={[{name: 'Jennifer Long', role: 'Document Specialist', text: 'Batch Conversion saves countless hours on bulk processing. Converts hundreds of files instantly!"},{name: 'Martin Price', role: 'IT Manager', text: 'Perfect for large-scale document standardization. Batch process efficiently.'},{name: 'Susan White', role: 'Administrator', text: 'Essential for managing bulk conversions. Fast and reliable.'}]} features={['Multiple formats','Bulk processing','Queue management','Parallel conversion','ZIP download','Progress tracking','Large file support','Format flexibility']} benefits={['Save time','Process at scale','Bulk efficiency','Standardization','Workflow automation','Quality preservation','Easy management','Cost effective']} faqs={[{q: 'How many files?', a: 'Unlimited! Process as many files as needed simultaneously."},{q: 'File size?', a: 'No limits! Handle files of any size in batch.'},{q: 'Formats?', a: 'PDF, Word, Excel, Images, PowerPoint and more.'},{q: 'Speed?', a: 'Parallel processing makes batch conversion extremely fast.'},{q: 'Download?', a: 'Download all converted files as single ZIP archive.'},{q: 'Preserve?', a: 'Yes! Formatting, quality, and content preserved perfectly.'},{q: 'Progress?', a: 'Real-time progress tracking for all files.'},{q: 'Automate?', a: 'Perfect for workflow automation and scheduled processing.'},{q: 'Is it free?', a: 'Completely free with unlimited batch conversions.'},{q: 'Enterprise?', a: 'Perfect for enterprise bulk processing needs.'}]} relatedTools={[{name: 'PDF to Word', slug: 'pdf-to-word'},{name: 'Word to PDF', slug: 'word-to-pdf'},{name: 'Compress PDF', slug: 'compress-pdf'}]} schema={schema} primaryKeyword="batch conversion" secondaryKeywords={['bulk conversion', 'batch PDF conversion', 'multiple file conversion']} />);
}
